__author__      = "Noreddine Kessa"
__copyright__   = "!"
__license__ = "MIT License"

from datetime import date
from variable import *
   
class DataManagerGenerator:

    def __init__(self, variableList=[], moduleName="DataManager", accessors_prefix="DataManager", CFileHeadersList=[], HFileHeaderList=[] ):
        self.variableList = variableList
        self.moduleName = moduleName
        self.CFileHeadersList = CFileHeadersList
        self.HFileHeaderList = HFileHeaderList
        self.accessors_prefix = accessors_prefix
        
        self.Disclamer_Header=f'/*!\n*Generated by DataManagerGenerator, do not edit manualy\n'
        self.Disclamer_Header+=f'*@file {moduleName}.h\n'
        self.Disclamer_Header+=f'*@date {date.today()}\n'
        self.Disclamer_Header+=f'*@author n.kessa\n'
        self.Disclamer_Header+=f'*@brief Manages device global configurations and device data flow between software modules.\n'
        self.Disclamer_Header+=f'*\n'
        self.Disclamer_Header+=f'*/\n\n'
        
        self.Disclamer_Source=f''
        self.Disclamer_Source+=f'/*!\n*Generated by DataManagerGenerator, do not edit manualy\n'
        self.Disclamer_Source+=f'*@file {moduleName}.c\n'
        self.Disclamer_Source+=f'*@date {date.today()}\n'
        self.Disclamer_Source+=f'*@author n.kessa\n'
        self.Disclamer_Source+=f'*@brief Manages device global configurations and device data flow between software modules.\n'
        self.Disclamer_Source+=f'*\n'
        self.Disclamer_Source+=f'*/\n\n'
        
        self.CPPGuardStart = f'\n#ifdef __cplusplus \nextern \"C\" \n{{ \n#endif		/* __cplusplus */ \n'
        self.CPPGuardEnd = f'#ifdef __cplusplus\n}}\n#endif		/* __cplusplus */\n'
        
        
    def generateHeaderFile(self):
        out = ""
        
        out+= self.Disclamer_Header
        
        #add guard
        out+=f'#ifndef {self.moduleName.upper()}_H \n'
        out+=f'#define {self.moduleName.upper()}_H \n'
        
        #add CPP guard
        out+=self.CPPGuardStart
        
        #add includes
        i = 0
        while i < len(self.HFileHeaderList):
            out+=self.HFileHeaderList[i]
            i = i + 1

        #add variables related stuff
        i = 0
        while i < len(self.variableList):
            self.variableList[i].accessors_prefix = self.accessors_prefix
            out+=f'/*****************************start of {self.variableList[i].name} definitions*************************************/\n'
            out+=self.variableList[i].get_header_definition()
            out+=f'/*****************************end of {self.variableList[i].name} definitions*************************************/\n\n'
            i = i + 1
        
        #close the cpp guard
        out+=self.CPPGuardEnd
        
        #close the guard
        out+=f'#endif /* {self.moduleName.upper()}_H */ \n'
  
        print("h file cintent" + out)
        f = open(f'{self.moduleName}.h', "w")
        f.write(out)
        f.close()
        
        
    def generateSourceFile(self):
    
        out=""
        out+= self.Disclamer_Source
        #add includes
        i = 0
        while i < len(self.CFileHeadersList):
            out+=self.CFileHeadersList[i]
            i = i + 1

        #add variables related stuff
        i = 0
        while i < len(self.variableList):
            self.variableList[i].accessors_prefix = self.accessors_prefix
            out+=f'/*****************************start of {self.variableList[i].name} definitions*************************************/\n'
            out+=self.variableList[i].get_source_implementation()
            out+=f'/*****************************end of {self.variableList[i].name} definitions*************************************/\n\n'
            i = i + 1
  
        print(out)
        f = open(f'{self.moduleName}.c', "w")
        f.write(out)
        f.close()
        
